Resources:
  fisrole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: fis.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEC2FullAccess
  fisroleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ssm:SendCommand
              - ssm:ListCommands
              - ssm:CancelCommands
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: fisroleDefaultPolicy
      Roles:
        - Ref: fisrole
  fistemplatedemocpustress:
    Type: AWS::FIS::ExperimentTemplate
    Properties:
      Description: Demo for injecting CPU stress via SSM
      RoleArn:
        Fn::GetAtt:
          - fisrole
          - Arn
      StopConditions:
        - Source: none
      Tags:
        Name: BurnCPUViaSSM
      Targets:
        instanceTargets:
          ResourceArns:
            - Fn::Join:
                - ""
                - "arn:aws:autoscaling:us-east-1:384612698411:autoScalingGroup:49124b04-d6d8-485e-a1c3-9823487ad486:autoScalingGroupName/WebApp1"
                  #- "arn:aws:ec2:"
                  #- Ref: AWS::Region
                  #- ":"
                  #- Ref: AWS::AccountId
                  #- :instance/
                  #- Ref: instance0B661231D
          ResourceType: aws:ec2:instance
          SelectionMode: ALL
      Actions:
        instanceActions:
          ActionId: aws:ssm:send-command
          Description: burn cpu vis SSM
          Parameters:
            documentArn:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ::document/AWSFIS-Run-CPU-Stress
            documentParameters: '{"DurationSeconds":"120"}'
            duration: PT2M
          Targets:
            Instances: instanceTargets
